name: Build image from develop
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@master
      - name: Login to gcloud
        id: gcloud
        uses: elgohr/gcloud-login-action@master
        with:
          account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      - name: Get release version
        id: get_version
        run: echo ${GITHUB_REF:7}
      - name: Build and publish image
        uses: docker/build-push-action@v1
        with:
          name: okcredit-42/playground-webapp
          username: ${{ steps.gcloud.outputs.username }}
          password: ${{ steps.gcloud.outputs.password }}
          registry: gcr.io
          tag_with_ref: true
          tag_with_sha: true