name: integration

on:
  push:
    branches:
      - develop

env:
  NAME: playground-webapp
  IMAGE: gcr.io/okcredit-42/playground-webapp

jobs:
  docker-build-push:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Login to docker registry
        run: gcloud auth configure-docker --quiet

      - name: Build image
        run: |
          COMMIT=${GITHUB_SHA:0:7}
          docker build -t $IMAGE:develop -t $IMAGE:sha-$COMMIT .

      - name: Push image
        run: docker push $IMAGE