name: integration

on:
  push:
    branches:
      - develop

env:
  NAME: playground-webapp

jobs:
  build-and-push-docker-image:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Test
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS
          cat $GOOGLE_APPLICATION_CREDENTIALS
          gcloud auth configure-docker --quiet
          echo $GITHUB_REF
          echo $GITHUB_SHA
#          docker build -t gcr.io/okcredit-42/${{ env.NAME }}:develop .
#          docker push gcr.io/okcredit-42/${{ env.NAME }}:develop