name: integration

on:
  push:
    branches:
      - develop

env:
  NAME: playground-webapp

jobs:
  build-and-push-docker-image:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Setup gcloud
#        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#        with:
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#          export_default_credentials: true

#      - name: Login to gcp container registry
#        run: gcloud --quiet auth configure-docker

#      - name: Check docker login
#        run: docker login gcr.io
      - name: Login to gcp container registry
        run: echo "${GCP_SA_KEY}" | base64 -d | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          registry: gcr.io
          repository: okcredit-42/${{ env.NAME }}
          tag_with_ref: true
          tag_with_sha: true